---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: application-webapp
  namespace: flux-system
spec:
  interval: 30s
  path: ./deploy/webapp
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  kubeConfig:
    secretRef:
      name: crossplane-workload-cluster-connection
  validation: client
