---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: application-prometheus
  namespace: flux-system
spec:
  dependsOn:
  - name: application-webapp
  interval: 30s
  path: ./deploy/monitoring
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
  - apiVersion: helm.toolkit.fluxcd.io/v2beta1
    kind: HelmRelease
    name: prometheus-helmrelease
    namespace: flux-system
  #
  # Prometheus is deployed using a HelmRelease.
  # Hence, the 'kubeConfig' field that points to the remote workload cluster is set in the HelmRelease manifest
  #
  validation: client
  timeout: 2m

