apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-credentials
  namespace: crossplane-system
spec:
  encryptedData:
    credentials: XXXXXXXXXXXXXX
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: aws-credentials
      namespace: crossplane-system

