serviceAccounts:
  server:
    name: prometheus-service-account
    annotations: 
      #
      # Set this to the ARN of an IAM role for the service account.
      # For details, refer to the documentation here: https://docs.aws.amazon.com/prometheus/latest/userguide/set-up-irsa.html
      #
      eks.amazonaws.com/role-arn: XXXXXXXXXX

nodeExporter:
    enabled: false
alertmanager:   
    enabled: false
pushgateway:
    enabled: false
kubeStateMetrics:
    enabled: false    

server:
    statefulSet:
        enabled: false
    persistentVolume:   
        enabled: false
        
    remoteWrite:
          #
          # Set the ID of an AMP workspace 
          #
        - url: https://aps-workspaces.us-west-2.amazonaws.com/workspaces/XXXXXXXXXXXXX/api/v1/remote_write
          sigv4:
            region: us-west-2
          queue_config:
            max_samples_per_send: 1000
            max_shards: 200
            capacity: 2500            